export const colors = [
    { color: "Red", icon: "❤️", hex: "#FF0000" },
    { color: "Blue", icon: "💧", hex: "#0000FF" },
    { color: "Green", icon: "🌿", hex: "#008000" },
    { color: "Yellow", icon: "🌟", hex: "#FFFF00" },
    { color: "Purple", icon: "💜", hex: "#800080" },
    { color: "Orange", icon: "🍊", hex: "#FFA500" },
    { color: "Pink", icon: "🌸", hex: "#FFC0CB" },
    { color: "Cyan", icon: "🌊", hex: "#00FFFF" },
    { color: "Gray", icon: "🌫️", hex: "#808080" },
    { color: "Black", icon: "⚫", hex: "#000000" },
    { color: "White", icon: "⚪", hex: "#FFFFFF" },
    { color: "Brown", icon: "🍂", hex: "#8B4513" },
    { color: "Indigo", icon: "💙", hex: "#4B0082" },
    { color: "Violet", icon: "💜", hex: "#EE82EE" },
    { color: "Gold", icon: "🏅", hex: "#FFD700" },
    { color: "Silver", icon: "🥈", hex: "#C0C0C0" },
    { color: "Teal", icon: "🌊", hex: "#008080" },
    { color: "Lime", icon: "🍋", hex: "#00FF00" },
    { color: "Maroon", icon: "🍒", hex: "#800000" },
    { color: "Olive", icon: "🍃", hex: "#808000" },
    { color: "Salmon", icon: "🐟", hex: "#FF6F61" },
    { color: "Emerald", icon: "💚", hex: "#33B679" },
    { color: "Sky Blue", icon: "☁️", hex: "#4B9CD3" },
    { color: "Blush", icon: "💗", hex: "#FF6F91" },
    { color: "Amethyst", icon: "💎", hex: "#9B59B6" },
    { color: "Mint", icon: "🌿", hex: "#1ABC9C" },
    { color: "Carrot", icon: "🥕", hex: "#FF8C00" },
    { color: "Lime Green", icon: "🍏", hex: "#B2D300" },
    { color: "Orchid", icon: "🌸", hex: "#8E44AD" },
    { color: "Hot Pink", icon: "🌷", hex: "#FF4F81" },
    { color: "Jade", icon: "🍃", hex: "#2ECC71" },
    { color: "Azure", icon: "🌊", hex: "#3498DB" },
    { color: "Apple", icon: "🍏", hex: "#A3D550" },
    { color: "Sky", icon: "🌌", hex: "#00BFFF" },
    { color: "Purple Heart", icon: "💜", hex: "#5B2C6F" }
];
