export const socialMediaListData = [
  { id: 1, name: 'Facebook', url: 'https://facebook.com', icon: 'facebook' },
  { id: 2, name: 'Twitter', url: 'https://twitter.com', icon: 'twitter' },
  { id: 3, name: 'Instagram', url: 'https://instagram.com', icon: 'instagram' },
  { id: 4, name: 'LinkedIn', url: 'https://linkedin.com', icon: 'linkedin' },
  { id: 5, name: 'YouTube', url: 'https://youtube.com', icon: 'youtube' },
  { id: 6, name: 'WhatsApp', url: 'https://whatsapp.com', icon: 'whatsapp' },
  { id: 7, name: 'Snapchat', url: 'https://snapchat.com', icon: 'snapchat' },
  { id: 8, name: 'Pinterest', url: 'https://pinterest.com', icon: 'pinterest' },
  { id: 9, name: 'Reddit', url: 'https://reddit.com', icon: 'reddit' },
  { id: 10, name: 'GitHub', url: 'https://github.com', icon: 'github' },
  { id: 11, name: 'TikTok', url: 'https://tiktok.com', icon: 'tiktok' },
  { id: 12, name: 'Discord', url: 'https://discord.com', icon: 'discord' },
  { id: 13, name: 'Telegram', url: 'https://telegram.org', icon: 'telegram' },
  { id: 14, name: 'Medium', url: 'https://medium.com', icon: 'medium' },
  { id: 15, name: 'Dribbble', url: 'https://dribbble.com', icon: 'dribbble' },
];
